"""empty message

Revision ID: c780a3aa4502
Revises: None
Create Date: 2016-10-14 14:51:14.999781

"""

# revision identifiers, used by Alembic.
revision = 'c780a3aa4502'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailylogstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailystatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hourlylogstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hourlystatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icpe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=12), nullable=True),
    sa.Column('alias', sa.String(length=20), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('mac')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_moderator', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weeklylogstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weeklystatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('geolat', sa.String(length=10), nullable=True),
    sa.Column('geolong', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['icpe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loginlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('ipaddr', sa.String(length=48), nullable=True),
    sa.Column('browser', sa.String(length=16), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('mailfrom', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nodeid', sa.Integer(), nullable=True),
    sa.Column('vid', sa.String(length=10), nullable=True),
    sa.Column('ptype', sa.String(length=10), nullable=True),
    sa.Column('pid', sa.String(length=10), nullable=True),
    sa.Column('generic_class', sa.String(length=10), nullable=True),
    sa.Column('productname', sa.String(length=30), nullable=True),
    sa.Column('brandname', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['icpe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodeevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nodeid', sa.Integer(), nullable=True),
    sa.Column('productname', sa.String(length=30), nullable=True),
    sa.Column('fonticon', sa.String(length=8), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['icpe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodeheat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nodeid', sa.Integer(), nullable=True),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('fonticon', sa.String(length=8), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['icpe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodeheatstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nodeid', sa.Integer(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['icpe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodenotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['icpe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodepower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nodeid', sa.Integer(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('fonticon', sa.String(length=8), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['icpe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodepowerstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nodeid', sa.Integer(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['icpe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodeclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('commandclass', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiddenfields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nodeclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hiddenfields')
    op.drop_table('nodeclass')
    op.drop_table('nodepowerstat')
    op.drop_table('nodepower')
    op.drop_table('nodenotes')
    op.drop_table('nodeheatstat')
    op.drop_table('nodeheat')
    op.drop_table('nodeevent')
    op.drop_table('node')
    op.drop_table('message')
    op.drop_table('loginlog')
    op.drop_table('location')
    op.drop_table('weeklystatistics')
    op.drop_table('weeklylogstatistics')
    op.drop_table('user')
    op.drop_table('icpe')
    op.drop_table('hourlystatistics')
    op.drop_table('hourlylogstatistics')
    op.drop_table('dailystatistics')
    op.drop_table('dailylogstatistics')
    ### end Alembic commands ###
