admin.py:socketio.on(
admin.py:socketio.on(
admin.py:socketio.on(
admin.py:socketio.on(
admin.py:socketio.on(
admin.py:socketio.on(
admin.py:socketio.on(
admin.py:socketio.on(
admin.py:socketio.on(
admin.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
data.py:socketio.on(
group.py:socketio.on(
group.py:socketio.on(
group.py:socketio.on(
group.py:socketio.on(
group.py:socketio.on(
group.py:socketio.on(
group.py:socketio.on(
group.py:socketio.on(
group.py:socketio.on(
icpe.py:socketio.on(
icpe.py:socketio.on(
icpe.py:socketio.on(
icpe.py:socketio.on(
icpe.py:socketio.on(
icpe.py:socketio.on(
icpe.py:socketio.on(
icpe.py:socketio.on(
mqtt.py:socketio.on(
mqtt.py:socketio.on(
mqtt.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
node.py:socketio.on(
plotly.py:socketio.on(
plotly.py:socketio.on(
plotly.py:socketio.on(
plotly.py:socketio.on(
plotly.py:socketio.on(
plotly.py:socketio.on(
plotly.py:socketio.on(
plotly.py:socketio.on(
sensor.py:socketio.on(
sensor.py:socketio.on(
sensor.py:socketio.on(
sensor.py:socketio.on(
sensor.py:socketio.on(
sensor.py:socketio.on(
sensor.py:socketio.on(
sensor.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
user.py:socketio.on(
